[package]
name = "nexus_integration"
version = "0.0.0"

[addresses]
# Bind the named address to a development placeholder or testnet address
nexus_integration = "_" 

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet" # or testnet depending on your target
subdir = "aptos-framework"
